kind: SwitchConfig
version: v1alpha1
kubeconfigName: "*.yaml"
kubeconfigStores:
- kind: filesystem
  id: fs1
  paths:
  - ~/.kube/configs/
  - ~/.k3d/
- kind: gke
  id: gke1
  config:
    authentication:
      authenticationType: gcloud
    projectIDs:
    - otl-ps-arch-otxecm
    - otl-cs-bash-csp
    - otl-s-sc-xecm  
    - otl-ps-cp-cv  
    - otl-ps-arch-otcs  
- kind: azure
  id: az1 
  config:
    subscriptionID: a421e4d3-0eb2-47fc-9476-e51f078b9ada      
